name: System Monitoring Reminder

on:
  workflow_dispatch: # Allows manual runs
  schedule:
    - cron: '0 8 * * 1' # Runs every Monday at 08:00 UTC (2:00 PM BST, 9:00 AM CEST / 8:00 AM CET)
    - cron: '0 8 * * 5' # Runs every Friday at 08:00 UTC (2:00 PM BST, 9:00 AM CEST / 8:00 AM CET)
    - cron: '0 4 * * *' # Runs at 10:00 AM BDT (4:00 AM UTC)
    - cron: '0 12 * * *' # Runs at 5:00 PM BDT (12:00 PM UTC)

env:
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # Set in repository secrets
  SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }} # Set in repository secrets

  SLACK_CHANNEL: "#your-channel-name" # Replace with actual Slack channel

jobs:
  send-rotation-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Uncomment this for debugging
      - name: Logs
        run: |
          echo "event: ${{ toJson(github.event) }}"
          echo "Secret: ${{ toJson(secrets) }}"
          echo "Environment: ${{ toJson(env) }}"
          echo "Runner: ${{ toJson(runner) }}"
          ls -la
          pwd

      - name: Fetch wiki content from public repository
        env:
          WIKI_PAGE_URL: "https://raw.githubusercontent.com/wiki/${{ github.repository }}/Rotation.md?token=${{ secrets.GITHUB_TOKEN }}"
          ROTATION_FILE: rotation.md
        run: |
          curl -s "${{ env.WIKI_PAGE_URL }}" > ${{ env.ROTATION_FILE }}
          cat ${{ env.ROTATION_FILE }}

      - name: Extract current guardian
        id: get_guardian
        run: |
          # Extract the Guardian name from the #Guardians section of the wiki Rotation.md file
          # Update this as per your wiki file structure
          GUARDIAN=$(awk '/# Guardians/,/^$/' rotation.md | grep '🔥' | sed 's/[[:space:]-]//g' | awk -F '🔥' '{print $1}')
          
          # Debugging output
          echo "Current Guardian: $GUARDIAN"

          # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/workflow-commands-for-github-actions#setting-an-environment-variable
          # Store the guardian in environment variables
          echo "GUARDIAN=$GUARDIAN" >> $GITHUB_ENV
          # TODO: GUARDIAN_ID....

      - name: Send Test Message
        if: github.event_name == 'workflow_dispatch'
        run: |
          MESSAGE="<!here> 
          :wave: Hello, World! :earth_africa:
          This is a test message to check if the reminder works. :robot_face:
          The current guardian is <@$GUARDIAN>. :shield:
          
          Please ignore this message. :sweat_smile:"
          
          curl -X POST \
            -H "Content-type: application/json" \
            --data "{
              \"channel\": \"${{ env.SLACK_CHANNEL_ID }}\",
              \"text\": \"${MESSAGE}\"
            }" \
            "${{ env.SLACK_WEBHOOK_URL }}"

      - name: Send Monday Reminder
        if: github.event.schedule == '0 8 * * 1' || github.event.schedule == '0 4 * * *'
        run: |
          MESSAGE="<!here> :robot_face: *System Monitoring Alert!* :rotating_light:
          Hey team! I need your help!
          This week's mighty guardian of system stability is <@$GUARDIAN>. :shield:
          Please check ${{ env.SLACK_CHANNEL }} and keep an eye on those pesky errors and bugs.
          Don't leave me alone! Without your help, I'm nothing! :pleading_face: :heart:"

          curl -X POST \
            -H "Content-type: application/json" \
            --data "{
              \"channel\": \"${{ env.SLACK_CHANNEL_ID }}\",
              \"text\": \"${MESSAGE}\"
            }" \
            "${{ env.SLACK_WEBHOOK_URL }}"

      - name: Send Friday Gratitude
        if: github.event.schedule == '0 8 * * 5' || github.event.schedule == '0 12 * * *'
        run: |
          MESSAGE="<!here> :trophy: *End of Week Celebration!* :confetti_ball:
          Hey <@$GUARDIAN>! You did an *amazing* job this week keeping our system safe. :fire:
          Before you grab that weekend drink :beers:, please update the next person in the wiki.
          I'll take care of the rest! Have a great weekend! :sunglasses: :sparkles:"

          curl -X POST \
            -H "Content-type: application/json" \
            --data "{
              \"channel\": \"${{ env.SLACK_CHANNEL_ID }}\",
              \"text\": \"${MESSAGE}\"
            }" \
            "${{ env.SLACK_WEBHOOK_URL }}"
